### ISSUE TITLE
Add `rustler_precompiled` and set up process of pre-compiling the Rust dependency

### ISSUE THREAD

**Issue by tmr08c** [avencera/fast_rss#17]
Since this project uses Rustler, I was curious if would you be open/interested in contributions to set up [`rusteler_precompiled`](https://hexdocs.pm/rustler_precompiled/RustlerPrecompiled.html). 

I am not sure the benefits (end-users not needing to have the Rust toolchain setup) would outweigh the costs (I think this is mostly the [updated release flow](https://hexdocs.pm/rustler_precompiled/precompilation_guide.html#the-release-flow)) for you, so I wanted to ask.

https://github.com/elixir-nx/explorer/pull/123 is an example of setting `rustler_precompiled` up for the Explorer package for reference of the scope of code changes.

**Comment by praveenperera** [comment]
Ya that would be fine with you, would you want to do the PR @tmr08c ?

**Comment by tmr08c** [comment]
Thank you for the interest, @praveenperera, I hope that it proves valuable. 

I am definitely interested in opening up a PR. 

Just to set expectations around timing - it may be about a week before I can get started on this. If anyone else sees this Issue and wants to make progress sooner, I don’t want to block them. If I don’t see any updates on the thread I’ll plan to proceed.

**Comment by praveenperera** [comment]
That sounds great @tmr08c
