### ISSUE TITLE
could not compile dependency :fast_rss

### ISSUE THREAD

**Issue by lrmpham** [avencera/fast_rss#3]
Hi, my project is getting this error when trying to compile fast_rss:
==> fast_rss
Compiling NIF crate :fastrss (native/fastrss)...
could not compile dependency :fast_rss, "mix compile" failed. You can recompile this dependency with "mix deps.compile fast_rss", update it with "mix deps.update fast_rss" or clean it with "mix deps.clean fast_rss"
** (ErlangError) Erlang error: :enoent
    (elixir) lib/system.ex:791: System.cmd("cargo", ["rustc", "--release"], [cd: "/Users/longpham/PlainJoe/mere-elixir/deps/fast_rss/native/fastrss", stderr_to_stdout: true, env: [{"CARGO_TARGET_DIR", "/Users/longpham/PlainJoe/mere-elixir/_build/dev/rustler_crates/fastrss"}], into: %IO.Stream{device: :standard_io, line_or_bytes: :line, raw: false}])
    lib/mix/tasks/compile.rustler.ex:59: Mix.Tasks.Compile.Rustler.compile_crate/1
    (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
    lib/mix/tasks/compile.rustler.ex:15: Mix.Tasks.Compile.Rustler.run/1
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
    (mix) lib/mix/tasks/compile.all.ex:73: Mix.Tasks.Compile.All.run_compiler/2
    (mix) lib/mix/tasks/compile.all.ex:53: Mix.Tasks.Compile.All.do_compile/4
    (mix) lib/mix/tasks/compile.all.ex:24: anonymous fn/1 in Mix.Tasks.Compile.All.run/1
I have installed the rustler compiler.  This just started happening but I have not made any changes.  Please advise.  Thanks.

**Comment by praveenperera** [comment]
Hey do you have the rust compiler installer? 

`curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`

**Comment by lrmpham** [comment]
Yes.  I ran that exact command prior to compile.

**Comment by praveenperera** [comment]
That's weird, the error is telling me your system can't find `cargo`

When you install rust compiler with the command above it should install `rustc`, `cargo` and `rustup`.

Can you show me the outputs for 

`rustc --version`

and 

`cargo -V`

**Comment by lrmpham** [comment]
It is compiling now.  It was a path issue.  It couldn't find rustc.  Sorry I'm new to the Elixir environment :).  Thanks for the help !

**Comment by praveenperera** [comment]
No problem, glad I could help
